# 01-HEADER
# menu
menu:
    home: /
    archive: /archives
    categories: /categories
    tags: /tags
    about: about
    profile: /profile
    video: /categories/photo/
    photo: /categories/photo/

# favicon, logo & index page background image
favicon: /img/favicon.ico
logo: 
    name: PC
    imag: /img/logo.jpg
banner: 
    bg: /malory/images/art/header-bg.jpg #站点banner背景图
    motto: Look around, take a photo——Gallery
cover: /malory/images/art/header-bg.jpg #文章统一封面图

# 02-PROLOADER
# animation: spinner, transition or cyclic
preloader:
    enable: true
    animation: transition

# 04-POST
# post_relate
relate:
    enable: true
    posts_limit: 10
    posts_excerpt: 120

    
livere: 
    enable: true
    livere_uid: 'sdd'
    

# post_excerpt
excerpt:
	enable: false
	length: 200

	
# post_imageDownload
image_download:
    enable: true
    
# post_share
# 注意浏览器的内容拦截插件
#https://www.addthis.com/
addThis:
    enable: false
    id: 
       
# 05-FOOTER
# social
social:
    rss: 
        url: /atom.xml
        icon: icon-s-rss
    github:
        url: http://github.com/pengshi12138
        icon: icon-s-github
    pinterest: 
        url: http://github.com/pengshi12138
        icon: icon-s-pinterest
    instagram:
        url: http://github.com/pengshi12138
        icon: icon-s-instagram
email: pengshi12138@outlook.com

# copyright  
since: 2024
author: PC

# 06-OTHERS
# rss
rss: /atom.xml

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 2